# Generated by Django 5.0.4 on 2024-04-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_datetime_project_isflagged_project_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dateTime',
            field=models.CharField(max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='height',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='isFlagged',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='make',
            field=models.CharField(max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='model',
            field=models.CharField(max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='speed',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='width',
            field=models.BigIntegerField(null=True),
        ),
    ]
