# Generated by Django 5.0.4 on 2024-04-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_project_datetime_alter_project_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='make',
        ),
        migrations.RemoveField(
            model_name='project',
            name='model',
        ),
        migrations.AlterField(
            model_name='project',
            name='lat',
            field=models.DecimalField(decimal_places=1000, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='lng',
            field=models.DecimalField(decimal_places=1000, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='speed',
            field=models.DecimalField(decimal_places=1000, max_digits=1000, null=True),
        ),
    ]
